- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "noidont@think.so"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "vp"
  tags:
  - git-personal
